name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Unit tests
        run: ./gradlew test
  report-detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install homebrew
        run: |
          sudo apt-get install build-essential curl file git
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      - name: Install detekt
        run: |
          brew update
          brew install detekt
      - name: Run detekt report
        run: detekt -c detekt/config.yml -r html:detekt/reports/detekt-report.html
      - name: Archive detekt report
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report.html
          path: detekt/reports/detekt-report.html
